/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  com.google.common.collect.ImmutableMap
 *  com.google.common.collect.ImmutableMap$Builder
 */
package net.minecraft.client.model.geom;

import com.google.common.collect.ImmutableMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;
import net.minecraft.client.model.AbstractEquineModel;
import net.minecraft.client.model.AllayModel;
import net.minecraft.client.model.ArmadilloModel;
import net.minecraft.client.model.ArmorStandArmorModel;
import net.minecraft.client.model.ArmorStandModel;
import net.minecraft.client.model.ArrowModel;
import net.minecraft.client.model.AxolotlModel;
import net.minecraft.client.model.BannerFlagModel;
import net.minecraft.client.model.BannerModel;
import net.minecraft.client.model.BatModel;
import net.minecraft.client.model.BeeModel;
import net.minecraft.client.model.BeeStingerModel;
import net.minecraft.client.model.BellModel;
import net.minecraft.client.model.BlazeModel;
import net.minecraft.client.model.BoatModel;
import net.minecraft.client.model.BoggedModel;
import net.minecraft.client.model.BookModel;
import net.minecraft.client.model.BreezeModel;
import net.minecraft.client.model.CamelModel;
import net.minecraft.client.model.CamelSaddleModel;
import net.minecraft.client.model.CatModel;
import net.minecraft.client.model.ChestModel;
import net.minecraft.client.model.ChickenModel;
import net.minecraft.client.model.CodModel;
import net.minecraft.client.model.ColdChickenModel;
import net.minecraft.client.model.ColdCowModel;
import net.minecraft.client.model.ColdPigModel;
import net.minecraft.client.model.CowModel;
import net.minecraft.client.model.CreakingModel;
import net.minecraft.client.model.CreeperModel;
import net.minecraft.client.model.DolphinModel;
import net.minecraft.client.model.DonkeyModel;
import net.minecraft.client.model.DrownedModel;
import net.minecraft.client.model.ElytraModel;
import net.minecraft.client.model.EndCrystalModel;
import net.minecraft.client.model.EndermanModel;
import net.minecraft.client.model.EndermiteModel;
import net.minecraft.client.model.EquineSaddleModel;
import net.minecraft.client.model.EvokerFangsModel;
import net.minecraft.client.model.FelineModel;
import net.minecraft.client.model.FoxModel;
import net.minecraft.client.model.FrogModel;
import net.minecraft.client.model.GhastModel;
import net.minecraft.client.model.GoatModel;
import net.minecraft.client.model.GuardianModel;
import net.minecraft.client.model.HappyGhastHarnessModel;
import net.minecraft.client.model.HappyGhastModel;
import net.minecraft.client.model.HoglinModel;
import net.minecraft.client.model.HumanoidArmorModel;
import net.minecraft.client.model.HumanoidModel;
import net.minecraft.client.model.IllagerModel;
import net.minecraft.client.model.IronGolemModel;
import net.minecraft.client.model.LavaSlimeModel;
import net.minecraft.client.model.LeashKnotModel;
import net.minecraft.client.model.LlamaModel;
import net.minecraft.client.model.LlamaSpitModel;
import net.minecraft.client.model.MinecartModel;
import net.minecraft.client.model.PandaModel;
import net.minecraft.client.model.ParrotModel;
import net.minecraft.client.model.PhantomModel;
import net.minecraft.client.model.PigModel;
import net.minecraft.client.model.PiglinHeadModel;
import net.minecraft.client.model.PiglinModel;
import net.minecraft.client.model.PlayerCapeModel;
import net.minecraft.client.model.PlayerEarsModel;
import net.minecraft.client.model.PlayerModel;
import net.minecraft.client.model.PolarBearModel;
import net.minecraft.client.model.PufferfishBigModel;
import net.minecraft.client.model.PufferfishMidModel;
import net.minecraft.client.model.PufferfishSmallModel;
import net.minecraft.client.model.RabbitModel;
import net.minecraft.client.model.RaftModel;
import net.minecraft.client.model.RavagerModel;
import net.minecraft.client.model.SalmonModel;
import net.minecraft.client.model.SheepFurModel;
import net.minecraft.client.model.SheepModel;
import net.minecraft.client.model.ShieldModel;
import net.minecraft.client.model.ShulkerBulletModel;
import net.minecraft.client.model.ShulkerModel;
import net.minecraft.client.model.SilverfishModel;
import net.minecraft.client.model.SkeletonModel;
import net.minecraft.client.model.SkullModel;
import net.minecraft.client.model.SlimeModel;
import net.minecraft.client.model.SnifferModel;
import net.minecraft.client.model.SnowGolemModel;
import net.minecraft.client.model.SpiderModel;
import net.minecraft.client.model.SpinAttackEffectModel;
import net.minecraft.client.model.SquidModel;
import net.minecraft.client.model.StriderModel;
import net.minecraft.client.model.TadpoleModel;
import net.minecraft.client.model.TridentModel;
import net.minecraft.client.model.TropicalFishModelA;
import net.minecraft.client.model.TropicalFishModelB;
import net.minecraft.client.model.TurtleModel;
import net.minecraft.client.model.VexModel;
import net.minecraft.client.model.VillagerModel;
import net.minecraft.client.model.WardenModel;
import net.minecraft.client.model.WarmCowModel;
import net.minecraft.client.model.WindChargeModel;
import net.minecraft.client.model.WitchModel;
import net.minecraft.client.model.WitherBossModel;
import net.minecraft.client.model.WolfModel;
import net.minecraft.client.model.ZombieVillagerModel;
import net.minecraft.client.model.dragon.DragonHeadModel;
import net.minecraft.client.model.dragon.EnderDragonModel;
import net.minecraft.client.model.geom.ModelLayerLocation;
import net.minecraft.client.model.geom.ModelLayers;
import net.minecraft.client.model.geom.builders.CubeDeformation;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshTransformer;
import net.minecraft.client.renderer.blockentity.BedRenderer;
import net.minecraft.client.renderer.blockentity.ConduitRenderer;
import net.minecraft.client.renderer.blockentity.DecoratedPotRenderer;
import net.minecraft.client.renderer.blockentity.HangingSignRenderer;
import net.minecraft.client.renderer.blockentity.SignRenderer;
import net.minecraft.client.renderer.entity.WitherSkullRenderer;
import net.minecraft.world.level.block.state.properties.WoodType;

public class LayerDefinitions {
    private static final CubeDeformation FISH_PATTERN_DEFORMATION = new CubeDeformation(0.008f);
    private static final CubeDeformation OUTER_ARMOR_DEFORMATION = new CubeDeformation(1.0f);
    private static final CubeDeformation INNER_ARMOR_DEFORMATION = new CubeDeformation(0.5f);

    public static Map<ModelLayerLocation, LayerDefinition> createRoots() {
        ImmutableMap.Builder builder = ImmutableMap.builder();
        LayerDefinition layerDefinition = LayerDefinition.create(HumanoidModel.createMesh(CubeDeformation.NONE, 0.0f), 64, 64);
        LayerDefinition layerDefinition2 = LayerDefinition.create(HumanoidArmorModel.createBodyLayer(OUTER_ARMOR_DEFORMATION), 64, 32);
        LayerDefinition layerDefinition3 = LayerDefinition.create(HumanoidArmorModel.createBodyLayer(new CubeDeformation(1.02f)), 64, 32);
        LayerDefinition layerDefinition4 = LayerDefinition.create(HumanoidArmorModel.createBodyLayer(INNER_ARMOR_DEFORMATION), 64, 32);
        LayerDefinition layerDefinition5 = MinecartModel.createBodyLayer();
        LayerDefinition layerDefinition6 = SkullModel.createMobHeadLayer();
        LayerDefinition layerDefinition7 = LayerDefinition.create(AbstractEquineModel.createBodyMesh(CubeDeformation.NONE), 64, 64);
        LayerDefinition layerDefinition8 = LayerDefinition.create(AbstractEquineModel.createBabyMesh(CubeDeformation.NONE), 64, 64);
        LayerDefinition layerDefinition9 = EquineSaddleModel.createSaddleLayer(false);
        LayerDefinition layerDefinition10 = EquineSaddleModel.createSaddleLayer(true);
        MeshTransformer meshTransformer = MeshTransformer.scaling(0.9375f);
        LayerDefinition layerDefinition11 = IllagerModel.createBodyLayer().apply(meshTransformer);
        LayerDefinition layerDefinition12 = AxolotlModel.createBodyLayer();
        LayerDefinition layerDefinition13 = BeeModel.createBodyLayer();
        LayerDefinition layerDefinition14 = CowModel.createBodyLayer();
        LayerDefinition layerDefinition15 = ColdChickenModel.createBodyLayer();
        LayerDefinition layerDefinition16 = ColdCowModel.createBodyLayer();
        LayerDefinition layerDefinition17 = ColdPigModel.createBodyLayer(CubeDeformation.NONE);
        LayerDefinition layerDefinition18 = ElytraModel.createLayer();
        LayerDefinition layerDefinition19 = LayerDefinition.create(FelineModel.createBodyMesh(CubeDeformation.NONE), 64, 32);
        LayerDefinition layerDefinition20 = layerDefinition19.apply(FelineModel.BABY_TRANSFORMER);
        LayerDefinition layerDefinition21 = LayerDefinition.create(FelineModel.createBodyMesh(new CubeDeformation(0.01f)), 64, 32);
        LayerDefinition layerDefinition22 = LayerDefinition.create(PiglinModel.createMesh(CubeDeformation.NONE), 64, 64);
        LayerDefinition layerDefinition23 = LayerDefinition.create(PiglinHeadModel.createHeadModel(), 64, 64);
        LayerDefinition layerDefinition24 = SkullModel.createHumanoidHeadLayer();
        LayerDefinition layerDefinition25 = LlamaModel.createBodyLayer(CubeDeformation.NONE);
        LayerDefinition layerDefinition26 = LlamaModel.createBodyLayer(new CubeDeformation(0.5f));
        LayerDefinition layerDefinition27 = StriderModel.createBodyLayer();
        LayerDefinition layerDefinition28 = HoglinModel.createBodyLayer();
        LayerDefinition layerDefinition29 = HoglinModel.createBabyLayer();
        LayerDefinition layerDefinition30 = SkeletonModel.createBodyLayer();
        LayerDefinition layerDefinition31 = LayerDefinition.create(VillagerModel.createBodyModel(), 64, 64).apply(meshTransformer);
        LayerDefinition layerDefinition32 = SpiderModel.createSpiderBodyLayer();
        LayerDefinition layerDefinition33 = ArmadilloModel.createBodyLayer();
        LayerDefinition layerDefinition34 = CamelModel.createBodyLayer();
        LayerDefinition layerDefinition35 = CamelSaddleModel.createSaddleLayer();
        LayerDefinition layerDefinition36 = ChickenModel.createBodyLayer();
        LayerDefinition layerDefinition37 = GoatModel.createBodyLayer();
        LayerDefinition layerDefinition38 = PandaModel.createBodyLayer();
        LayerDefinition layerDefinition39 = PigModel.createBodyLayer(CubeDeformation.NONE);
        LayerDefinition layerDefinition40 = PigModel.createBodyLayer(new CubeDeformation(0.5f));
        LayerDefinition layerDefinition41 = SheepModel.createBodyLayer();
        LayerDefinition layerDefinition42 = SheepFurModel.createFurLayer();
        LayerDefinition layerDefinition43 = SnifferModel.createBodyLayer();
        LayerDefinition layerDefinition44 = TurtleModel.createBodyLayer();
        LayerDefinition layerDefinition45 = WarmCowModel.createBodyLayer();
        LayerDefinition layerDefinition46 = LayerDefinition.create(WolfModel.createMeshDefinition(CubeDeformation.NONE), 64, 32);
        LayerDefinition layerDefinition47 = LayerDefinition.create(WolfModel.createMeshDefinition(new CubeDeformation(0.2f)), 64, 32);
        LayerDefinition layerDefinition48 = ZombieVillagerModel.createBodyLayer();
        LayerDefinition layerDefinition49 = ArmorStandModel.createBodyLayer();
        LayerDefinition layerDefinition50 = ArmorStandArmorModel.createBodyLayer(INNER_ARMOR_DEFORMATION);
        LayerDefinition layerDefinition51 = ArmorStandArmorModel.createBodyLayer(OUTER_ARMOR_DEFORMATION);
        LayerDefinition layerDefinition52 = DrownedModel.createBodyLayer(CubeDeformation.NONE);
        LayerDefinition layerDefinition53 = DrownedModel.createBodyLayer(new CubeDeformation(0.25f));
        LayerDefinition layerDefinition54 = SquidModel.createBodyLayer();
        LayerDefinition layerDefinition55 = DolphinModel.createBodyLayer();
        LayerDefinition layerDefinition56 = SalmonModel.createBodyLayer();
        builder.put((Object)ModelLayers.ALLAY, (Object)AllayModel.createBodyLayer());
        builder.put((Object)ModelLayers.ARMADILLO, (Object)layerDefinition33);
        builder.put((Object)ModelLayers.ARMADILLO_BABY, (Object)layerDefinition33.apply(ArmadilloModel.BABY_TRANSFORMER));
        builder.put((Object)ModelLayers.ARMOR_STAND, (Object)layerDefinition49);
        builder.put((Object)ModelLayers.ARMOR_STAND_INNER_ARMOR, (Object)layerDefinition50);
        builder.put((Object)ModelLayers.ARMOR_STAND_OUTER_ARMOR, (Object)layerDefinition51);
        builder.put((Object)ModelLayers.ARMOR_STAND_SMALL, (Object)layerDefinition49.apply(HumanoidModel.BABY_TRANSFORMER));
        builder.put((Object)ModelLayers.ARMOR_STAND_SMALL_INNER_ARMOR, (Object)layerDefinition50.apply(HumanoidModel.BABY_TRANSFORMER));
        builder.put((Object)ModelLayers.ARMOR_STAND_SMALL_OUTER_ARMOR, (Object)layerDefinition51.apply(HumanoidModel.BABY_TRANSFORMER));
        builder.put((Object)ModelLayers.ARROW, (Object)ArrowModel.createBodyLayer());
        builder.put((Object)ModelLayers.AXOLOTL, (Object)layerDefinition12);
        builder.put((Object)ModelLayers.AXOLOTL_BABY, (Object)layerDefinition12.apply(AxolotlModel.BABY_TRANSFORMER));
        builder.put((Object)ModelLayers.STANDING_BANNER, (Object)BannerModel.createBodyLayer(true));
        builder.put((Object)ModelLayers.WALL_BANNER, (Object)BannerModel.createBodyLayer(false));
        builder.put((Object)ModelLayers.STANDING_BANNER_FLAG, (Object)BannerFlagModel.createFlagLayer(true));
        builder.put((Object)ModelLayers.WALL_BANNER_FLAG, (Object)BannerFlagModel.createFlagLayer(false));
        builder.put((Object)ModelLayers.BAT, (Object)BatModel.createBodyLayer());
        builder.put((Object)ModelLayers.BED_FOOT, (Object)BedRenderer.createFootLayer());
        builder.put((Object)ModelLayers.BED_HEAD, (Object)BedRenderer.createHeadLayer());
        builder.put((Object)ModelLayers.BEE, (Object)layerDefinition13);
        builder.put((Object)ModelLayers.BEE_BABY, (Object)layerDefinition13.apply(BeeModel.BABY_TRANSFORMER));
        builder.put((Object)ModelLayers.BEE_STINGER, (Object)BeeStingerModel.createBodyLayer());
        builder.put((Object)ModelLayers.BELL, (Object)BellModel.createBodyLayer());
        builder.put((Object)ModelLayers.BLAZE, (Object)BlazeModel.createBodyLayer());
        builder.put((Object)ModelLayers.BOAT_WATER_PATCH, (Object)BoatModel.createWaterPatch());
        builder.put((Object)ModelLayers.BOGGED, (Object)BoggedModel.createBodyLayer());
        builder.put((Object)ModelLayers.BOGGED_INNER_ARMOR, (Object)layerDefinition4);
        builder.put((Object)ModelLayers.BOGGED_OUTER_ARMOR, (Object)layerDefinition2);
        builder.put((Object)ModelLayers.BOGGED_OUTER_LAYER, (Object)LayerDefinition.create(HumanoidModel.createMesh(new CubeDeformation(0.2f), 0.0f), 64, 32));
        builder.put((Object)ModelLayers.BOOK, (Object)BookModel.createBodyLayer());
        builder.put((Object)ModelLayers.BREEZE, (Object)BreezeModel.createBodyLayer(32, 32));
        builder.put((Object)ModelLayers.BREEZE_WIND, (Object)BreezeModel.createBodyLayer(128, 128));
        builder.put((Object)ModelLayers.CAT, (Object)layerDefinition19.apply(CatModel.CAT_TRANSFORMER));
        builder.put((Object)ModelLayers.CAT_BABY, (Object)layerDefinition20.apply(CatModel.CAT_TRANSFORMER));
        builder.put((Object)ModelLayers.CAT_COLLAR, (Object)layerDefinition21.apply(CatModel.CAT_TRANSFORMER));
        builder.put((Object)ModelLayers.CAT_BABY_COLLAR, (Object)layerDefinition21.apply(FelineModel.BABY_TRANSFORMER).apply(CatModel.CAT_TRANSFORMER));
        builder.put((Object)ModelLayers.CAMEL, (Object)layerDefinition34);
        builder.put((Object)ModelLayers.CAMEL_BABY, (Object)layerDefinition34.apply(CamelModel.BABY_TRANSFORMER));
        builder.put((Object)ModelLayers.CAMEL_SADDLE, (Object)layerDefinition35);
        builder.put((Object)ModelLayers.CAMEL_BABY_SADDLE, (Object)layerDefinition35.apply(CamelModel.BABY_TRANSFORMER));
        builder.put((Object)ModelLayers.CAVE_SPIDER, (Object)layerDefinition32.apply(MeshTransformer.scaling(0.7f)));
        builder.put((Object)ModelLayers.CHEST, (Object)ChestModel.createSingleBodyLayer());
        builder.put((Object)ModelLayers.CHEST_MINECART, (Object)layerDefinition5);
        builder.put((Object)ModelLayers.CHICKEN, (Object)layerDefinition36);
        builder.put((Object)ModelLayers.CHICKEN_BABY, (Object)layerDefinition36.apply(ChickenModel.BABY_TRANSFORMER));
        builder.put((Object)ModelLayers.COD, (Object)CodModel.createBodyLayer());
        builder.put((Object)ModelLayers.COLD_CHICKEN, (Object)layerDefinition15);
        builder.put((Object)ModelLayers.COLD_CHICKEN_BABY, (Object)layerDefinition15.apply(ChickenModel.BABY_TRANSFORMER));
        builder.put((Object)ModelLayers.COLD_COW, (Object)layerDefinition16);
        builder.put((Object)ModelLayers.COLD_COW_BABY, (Object)layerDefinition16.apply(CowModel.BABY_TRANSFORMER));
        builder.put((Object)ModelLayers.COLD_PIG, (Object)layerDefinition17);
        builder.put((Object)ModelLayers.COLD_PIG_BABY, (Object)layerDefinition17.apply(PigModel.BABY_TRANSFORMER));
        builder.put((Object)ModelLayers.COMMAND_BLOCK_MINECART, (Object)layerDefinition5);
        builder.put((Object)ModelLayers.CONDUIT_EYE, (Object)ConduitRenderer.createEyeLayer());
        builder.put((Object)ModelLayers.CONDUIT_WIND, (Object)ConduitRenderer.createWindLayer());
        builder.put((Object)ModelLayers.CONDUIT_SHELL, (Object)ConduitRenderer.createShellLayer());
        builder.put((Object)ModelLayers.CONDUIT_CAGE, (Object)ConduitRenderer.createCageLayer());
        builder.put((Object)ModelLayers.COW, (Object)layerDefinition14);
        builder.put((Object)ModelLayers.COW_BABY, (Object)layerDefinition14.apply(CowModel.BABY_TRANSFORMER));
        builder.put((Object)ModelLayers.CREAKING, (Object)CreakingModel.createBodyLayer());
        builder.put((Object)ModelLayers.CREEPER, (Object)CreeperModel.createBodyLayer(CubeDeformation.NONE));
        builder.put((Object)ModelLayers.CREEPER_ARMOR, (Object)CreeperModel.createBodyLayer(new CubeDeformation(2.0f)));
        builder.put((Object)ModelLayers.CREEPER_HEAD, (Object)layerDefinition6);
        builder.put((Object)ModelLayers.DECORATED_POT_BASE, (Object)DecoratedPotRenderer.createBaseLayer());
        builder.put((Object)ModelLayers.DECORATED_POT_SIDES, (Object)DecoratedPotRenderer.createSidesLayer());
        builder.put((Object)ModelLayers.DOLPHIN, (Object)layerDefinition55);
        builder.put((Object)ModelLayers.DOLPHIN_BABY, (Object)layerDefinition55.apply(DolphinModel.BABY_TRANSFORMER));
        builder.put((Object)ModelLayers.DONKEY, (Object)DonkeyModel.createBodyLayer(0.87f));
        builder.put((Object)ModelLayers.DONKEY_BABY, (Object)DonkeyModel.createBabyLayer(0.87f));
        builder.put((Object)ModelLayers.DONKEY_SADDLE, (Object)DonkeyModel.createSaddleLayer(0.87f, false));
        builder.put((Object)ModelLayers.DONKEY_BABY_SADDLE, (Object)DonkeyModel.createSaddleLayer(0.87f, true));
        builder.put((Object)ModelLayers.DOUBLE_CHEST_LEFT, (Object)ChestModel.createDoubleBodyLeftLayer());
        builder.put((Object)ModelLayers.DOUBLE_CHEST_RIGHT, (Object)ChestModel.createDoubleBodyRightLayer());
        builder.put((Object)ModelLayers.DRAGON_SKULL, (Object)DragonHeadModel.createHeadLayer());
        builder.put((Object)ModelLayers.DROWNED, (Object)layerDefinition52);
        builder.put((Object)ModelLayers.DROWNED_INNER_ARMOR, (Object)layerDefinition4);
        builder.put((Object)ModelLayers.DROWNED_OUTER_ARMOR, (Object)layerDefinition4);
        builder.put((Object)ModelLayers.DROWNED_OUTER_LAYER, (Object)layerDefinition53);
        builder.put((Object)ModelLayers.DROWNED_BABY, (Object)layerDefinition52.apply(HumanoidModel.BABY_TRANSFORMER));
        builder.put((Object)ModelLayers.DROWNED_BABY_INNER_ARMOR, (Object)layerDefinition4.apply(HumanoidModel.BABY_TRANSFORMER));
        builder.put((Object)ModelLayers.DROWNED_BABY_OUTER_ARMOR, (Object)layerDefinition4.apply(HumanoidModel.BABY_TRANSFORMER));
        builder.put((Object)ModelLayers.DROWNED_BABY_OUTER_LAYER, (Object)layerDefinition53.apply(HumanoidModel.BABY_TRANSFORMER));
        builder.put((Object)ModelLayers.ELDER_GUARDIAN, (Object)GuardianModel.createElderGuardianLayer());
        builder.put((Object)ModelLayers.ELYTRA, (Object)layerDefinition18);
        builder.put((Object)ModelLayers.ELYTRA_BABY, (Object)layerDefinition18.apply(ElytraModel.BABY_TRANSFORMER));
        builder.put((Object)ModelLayers.ENDERMAN, (Object)EndermanModel.createBodyLayer());
        builder.put((Object)ModelLayers.ENDERMITE, (Object)EndermiteModel.createBodyLayer());
        builder.put((Object)ModelLayers.ENDER_DRAGON, (Object)EnderDragonModel.createBodyLayer());
        builder.put((Object)ModelLayers.END_CRYSTAL, (Object)EndCrystalModel.createBodyLayer());
        builder.put((Object)ModelLayers.EVOKER, (Object)layerDefinition11);
        builder.put((Object)ModelLayers.EVOKER_FANGS, (Object)EvokerFangsModel.createBodyLayer());
        builder.put((Object)ModelLayers.FOX, (Object)FoxModel.createBodyLayer());
        builder.put((Object)ModelLayers.FOX_BABY, (Object)FoxModel.createBodyLayer().apply(FoxModel.BABY_TRANSFORMER));
        builder.put((Object)ModelLayers.FROG, (Object)FrogModel.createBodyLayer());
        builder.put((Object)ModelLayers.FURNACE_MINECART, (Object)layerDefinition5);
        builder.put((Object)ModelLayers.GHAST, (Object)GhastModel.createBodyLayer());
        MeshTransformer meshTransformer2 = MeshTransformer.scaling(6.0f);
        builder.put((Object)ModelLayers.GIANT, (Object)layerDefinition.apply(meshTransformer2));
        builder.put((Object)ModelLayers.GIANT_INNER_ARMOR, (Object)layerDefinition4.apply(meshTransformer2));
        builder.put((Object)ModelLayers.GIANT_OUTER_ARMOR, (Object)layerDefinition2.apply(meshTransformer2));
        builder.put((Object)ModelLayers.GLOW_SQUID, (Object)layerDefinition54);
        builder.put((Object)ModelLayers.GLOW_SQUID_BABY, (Object)layerDefinition54.apply(SquidModel.BABY_TRANSFORMER));
        builder.put((Object)ModelLayers.GOAT, (Object)layerDefinition37);
        builder.put((Object)ModelLayers.GOAT_BABY, (Object)layerDefinition37.apply(GoatModel.BABY_TRANSFORMER));
        builder.put((Object)ModelLayers.GUARDIAN, (Object)GuardianModel.createBodyLayer());
        builder.put((Object)ModelLayers.HAPPY_GHAST, (Object)HappyGhastModel.createBodyLayer(false, CubeDeformation.NONE));
        builder.put((Object)ModelLayers.HAPPY_GHAST_BABY, (Object)HappyGhastModel.createBodyLayer(true, CubeDeformation.NONE).apply(HappyGhastModel.BABY_TRANSFORMER));
        builder.put((Object)ModelLayers.HAPPY_GHAST_HARNESS, (Object)HappyGhastHarnessModel.createHarnessLayer(false));
        builder.put((Object)ModelLayers.HAPPY_GHAST_BABY_HARNESS, (Object)HappyGhastHarnessModel.createHarnessLayer(true).apply(HappyGhastModel.BABY_TRANSFORMER));
        builder.put((Object)ModelLayers.HAPPY_GHAST_ROPES, (Object)HappyGhastModel.createBodyLayer(false, new CubeDeformation(0.2f)));
        builder.put((Object)ModelLayers.HAPPY_GHAST_BABY_ROPES, (Object)HappyGhastModel.createBodyLayer(true, new CubeDeformation(0.2f)).apply(HappyGhastModel.BABY_TRANSFORMER));
        builder.put((Object)ModelLayers.HOGLIN, (Object)layerDefinition28);
        builder.put((Object)ModelLayers.HOGLIN_BABY, (Object)layerDefinition29);
        builder.put((Object)ModelLayers.HOPPER_MINECART, (Object)layerDefinition5);
        MeshTransformer meshTransformer3 = MeshTransformer.scaling(1.1f);
        builder.put((Object)ModelLayers.HORSE, (Object)layerDefinition7.apply(meshTransformer3));
        builder.put((Object)ModelLayers.HORSE_BABY, (Object)layerDefinition8.apply(meshTransformer3));
        builder.put((Object)ModelLayers.HORSE_ARMOR, (Object)LayerDefinition.create(AbstractEquineModel.createBodyMesh(new CubeDeformation(0.1f)), 64, 64).apply(meshTransformer3));
        builder.put((Object)ModelLayers.HORSE_BABY_ARMOR, (Object)LayerDefinition.create(AbstractEquineModel.createBabyMesh(new CubeDeformation(0.1f)), 64, 64).apply(meshTransformer3));
        builder.put((Object)ModelLayers.HORSE_SADDLE, (Object)layerDefinition9.apply(meshTransformer3));
        builder.put((Object)ModelLayers.HORSE_BABY_SADDLE, (Object)layerDefinition10.apply(meshTransformer3));
        MeshTransformer meshTransformer4 = MeshTransformer.scaling(1.0625f);
        builder.put((Object)ModelLayers.HUSK, (Object)layerDefinition.apply(meshTransformer4));
        builder.put((Object)ModelLayers.HUSK_INNER_ARMOR, (Object)layerDefinition4.apply(meshTransformer4));
        builder.put((Object)ModelLayers.HUSK_OUTER_ARMOR, (Object)layerDefinition2.apply(meshTransformer4));
        builder.put((Object)ModelLayers.HUSK_BABY, (Object)layerDefinition.apply(HumanoidModel.BABY_TRANSFORMER).apply(meshTransformer4));
        builder.put((Object)ModelLayers.HUSK_BABY_INNER_ARMOR, (Object)layerDefinition4.apply(HumanoidModel.BABY_TRANSFORMER).apply(meshTransformer4));
        builder.put((Object)ModelLayers.HUSK_BABY_OUTER_ARMOR, (Object)layerDefinition2.apply(HumanoidModel.BABY_TRANSFORMER).apply(meshTransformer4));
        builder.put((Object)ModelLayers.ILLUSIONER, (Object)layerDefinition11);
        builder.put((Object)ModelLayers.IRON_GOLEM, (Object)IronGolemModel.createBodyLayer());
        builder.put((Object)ModelLayers.LEASH_KNOT, (Object)LeashKnotModel.createBodyLayer());
        builder.put((Object)ModelLayers.LLAMA, (Object)layerDefinition25);
        builder.put((Object)ModelLayers.LLAMA_BABY, (Object)layerDefinition25.apply(LlamaModel.BABY_TRANSFORMER));
        builder.put((Object)ModelLayers.LLAMA_DECOR, (Object)layerDefinition26);
        builder.put((Object)ModelLayers.LLAMA_BABY_DECOR, (Object)layerDefinition26.apply(LlamaModel.BABY_TRANSFORMER));
        builder.put((Object)ModelLayers.LLAMA_SPIT, (Object)LlamaSpitModel.createBodyLayer());
        builder.put((Object)ModelLayers.MAGMA_CUBE, (Object)LavaSlimeModel.createBodyLayer());
        builder.put((Object)ModelLayers.MINECART, (Object)layerDefinition5);
        builder.put((Object)ModelLayers.MOOSHROOM, (Object)layerDefinition14);
        builder.put((Object)ModelLayers.MOOSHROOM_BABY, (Object)layerDefinition14.apply(CowModel.BABY_TRANSFORMER));
        builder.put((Object)ModelLayers.MULE, (Object)DonkeyModel.createBodyLayer(0.92f));
        builder.put((Object)ModelLayers.MULE_BABY, (Object)DonkeyModel.createBabyLayer(0.92f));
        builder.put((Object)ModelLayers.MULE_SADDLE, (Object)DonkeyModel.createSaddleLayer(0.92f, false));
        builder.put((Object)ModelLayers.MULE_BABY_SADDLE, (Object)DonkeyModel.createSaddleLayer(0.92f, true));
        builder.put((Object)ModelLayers.OCELOT, (Object)layerDefinition19);
        builder.put((Object)ModelLayers.OCELOT_BABY, (Object)layerDefinition20);
        builder.put((Object)ModelLayers.PANDA, (Object)layerDefinition38);
        builder.put((Object)ModelLayers.PANDA_BABY, (Object)layerDefinition38.apply(PandaModel.BABY_TRANSFORMER));
        builder.put((Object)ModelLayers.PARROT, (Object)ParrotModel.createBodyLayer());
        builder.put((Object)ModelLayers.PHANTOM, (Object)PhantomModel.createBodyLayer());
        builder.put((Object)ModelLayers.PIG, (Object)layerDefinition39);
        builder.put((Object)ModelLayers.PIG_BABY, (Object)layerDefinition39.apply(PigModel.BABY_TRANSFORMER));
        builder.put((Object)ModelLayers.PIG_SADDLE, (Object)layerDefinition40);
        builder.put((Object)ModelLayers.PIG_BABY_SADDLE, (Object)layerDefinition40.apply(PigModel.BABY_TRANSFORMER));
        builder.put((Object)ModelLayers.PIGLIN, (Object)layerDefinition22);
        builder.put((Object)ModelLayers.PIGLIN_INNER_ARMOR, (Object)layerDefinition4);
        builder.put((Object)ModelLayers.PIGLIN_OUTER_ARMOR, (Object)layerDefinition3);
        builder.put((Object)ModelLayers.PIGLIN_BRUTE, (Object)layerDefinition22);
        builder.put((Object)ModelLayers.PIGLIN_BRUTE_INNER_ARMOR, (Object)layerDefinition4);
        builder.put((Object)ModelLayers.PIGLIN_BRUTE_OUTER_ARMOR, (Object)layerDefinition3);
        builder.put((Object)ModelLayers.PIGLIN_BABY, (Object)layerDefinition22.apply(HumanoidModel.BABY_TRANSFORMER));
        builder.put((Object)ModelLayers.PIGLIN_BABY_INNER_ARMOR, (Object)layerDefinition4.apply(HumanoidModel.BABY_TRANSFORMER));
        builder.put((Object)ModelLayers.PIGLIN_BABY_OUTER_ARMOR, (Object)layerDefinition3.apply(HumanoidModel.BABY_TRANSFORMER));
        builder.put((Object)ModelLayers.PIGLIN_HEAD, (Object)layerDefinition23);
        builder.put((Object)ModelLayers.PILLAGER, (Object)layerDefinition11);
        builder.put((Object)ModelLayers.PLAYER, (Object)LayerDefinition.create(PlayerModel.createMesh(CubeDeformation.NONE, false), 64, 64));
        builder.put((Object)ModelLayers.PLAYER_EARS, (Object)PlayerEarsModel.createEarsLayer());
        builder.put((Object)ModelLayers.PLAYER_CAPE, (Object)PlayerCapeModel.createCapeLayer());
        builder.put((Object)ModelLayers.PLAYER_HEAD, (Object)layerDefinition24);
        builder.put((Object)ModelLayers.PLAYER_INNER_ARMOR, (Object)layerDefinition4);
        builder.put((Object)ModelLayers.PLAYER_OUTER_ARMOR, (Object)layerDefinition2);
        builder.put((Object)ModelLayers.PLAYER_SLIM, (Object)LayerDefinition.create(PlayerModel.createMesh(CubeDeformation.NONE, true), 64, 64));
        builder.put((Object)ModelLayers.PLAYER_SLIM_INNER_ARMOR, (Object)layerDefinition4);
        builder.put((Object)ModelLayers.PLAYER_SLIM_OUTER_ARMOR, (Object)layerDefinition2);
        builder.put((Object)ModelLayers.PLAYER_SPIN_ATTACK, (Object)SpinAttackEffectModel.createLayer());
        builder.put((Object)ModelLayers.POLAR_BEAR, (Object)PolarBearModel.createBodyLayer(false));
        builder.put((Object)ModelLayers.POLAR_BEAR_BABY, (Object)PolarBearModel.createBodyLayer(true));
        builder.put((Object)ModelLayers.PUFFERFISH_BIG, (Object)PufferfishBigModel.createBodyLayer());
        builder.put((Object)ModelLayers.PUFFERFISH_MEDIUM, (Object)PufferfishMidModel.createBodyLayer());
        builder.put((Object)ModelLayers.PUFFERFISH_SMALL, (Object)PufferfishSmallModel.createBodyLayer());
        builder.put((Object)ModelLayers.RABBIT, (Object)RabbitModel.createBodyLayer(false));
        builder.put((Object)ModelLayers.RABBIT_BABY, (Object)RabbitModel.createBodyLayer(true));
        builder.put((Object)ModelLayers.RAVAGER, (Object)RavagerModel.createBodyLayer());
        builder.put((Object)ModelLayers.SALMON, (Object)layerDefinition56);
        builder.put((Object)ModelLayers.SALMON_SMALL, (Object)layerDefinition56.apply(SalmonModel.SMALL_TRANSFORMER));
        builder.put((Object)ModelLayers.SALMON_LARGE, (Object)layerDefinition56.apply(SalmonModel.LARGE_TRANSFORMER));
        builder.put((Object)ModelLayers.SHEEP, (Object)layerDefinition41);
        builder.put((Object)ModelLayers.SHEEP_BABY, (Object)layerDefinition41.apply(SheepModel.BABY_TRANSFORMER));
        builder.put((Object)ModelLayers.SHEEP_WOOL, (Object)layerDefinition42);
        builder.put((Object)ModelLayers.SHEEP_BABY_WOOL, (Object)layerDefinition42.apply(SheepModel.BABY_TRANSFORMER));
        builder.put((Object)ModelLayers.SHEEP_WOOL_UNDERCOAT, (Object)layerDefinition41);
        builder.put((Object)ModelLayers.SHEEP_BABY_WOOL_UNDERCOAT, (Object)layerDefinition41.apply(SheepModel.BABY_TRANSFORMER));
        builder.put((Object)ModelLayers.SHIELD, (Object)ShieldModel.createLayer());
        builder.put((Object)ModelLayers.SHULKER, (Object)ShulkerModel.createBodyLayer());
        builder.put((Object)ModelLayers.SHULKER_BOX, (Object)ShulkerModel.createBoxLayer());
        builder.put((Object)ModelLayers.SHULKER_BULLET, (Object)ShulkerBulletModel.createBodyLayer());
        builder.put((Object)ModelLayers.SILVERFISH, (Object)SilverfishModel.createBodyLayer());
        builder.put((Object)ModelLayers.SKELETON, (Object)layerDefinition30);
        builder.put((Object)ModelLayers.SKELETON_INNER_ARMOR, (Object)layerDefinition4);
        builder.put((Object)ModelLayers.SKELETON_OUTER_ARMOR, (Object)layerDefinition2);
        builder.put((Object)ModelLayers.SKELETON_HORSE, (Object)layerDefinition7);
        builder.put((Object)ModelLayers.SKELETON_HORSE_BABY, (Object)layerDefinition8);
        builder.put((Object)ModelLayers.SKELETON_HORSE_SADDLE, (Object)layerDefinition9);
        builder.put((Object)ModelLayers.SKELETON_HORSE_BABY_SADDLE, (Object)layerDefinition10);
        builder.put((Object)ModelLayers.SKELETON_SKULL, (Object)layerDefinition6);
        builder.put((Object)ModelLayers.SLIME, (Object)SlimeModel.createInnerBodyLayer());
        builder.put((Object)ModelLayers.SLIME_OUTER, (Object)SlimeModel.createOuterBodyLayer());
        builder.put((Object)ModelLayers.SNIFFER, (Object)layerDefinition43);
        builder.put((Object)ModelLayers.SNIFFER_BABY, (Object)layerDefinition43.apply(SnifferModel.BABY_TRANSFORMER));
        builder.put((Object)ModelLayers.SNOW_GOLEM, (Object)SnowGolemModel.createBodyLayer());
        builder.put((Object)ModelLayers.SPAWNER_MINECART, (Object)layerDefinition5);
        builder.put((Object)ModelLayers.SPIDER, (Object)layerDefinition32);
        builder.put((Object)ModelLayers.SQUID, (Object)layerDefinition54);
        builder.put((Object)ModelLayers.SQUID_BABY, (Object)layerDefinition54.apply(SquidModel.BABY_TRANSFORMER));
        builder.put((Object)ModelLayers.STRAY, (Object)layerDefinition30);
        builder.put((Object)ModelLayers.STRAY_INNER_ARMOR, (Object)layerDefinition4);
        builder.put((Object)ModelLayers.STRAY_OUTER_ARMOR, (Object)layerDefinition2);
        builder.put((Object)ModelLayers.STRAY_OUTER_LAYER, (Object)LayerDefinition.create(HumanoidModel.createMesh(new CubeDeformation(0.25f), 0.0f), 64, 32));
        builder.put((Object)ModelLayers.STRIDER, (Object)layerDefinition27);
        builder.put((Object)ModelLayers.STRIDER_SADDLE, (Object)layerDefinition27);
        builder.put((Object)ModelLayers.STRIDER_BABY, (Object)layerDefinition27.apply(StriderModel.BABY_TRANSFORMER));
        builder.put((Object)ModelLayers.STRIDER_BABY_SADDLE, (Object)layerDefinition27.apply(StriderModel.BABY_TRANSFORMER));
        builder.put((Object)ModelLayers.TADPOLE, (Object)TadpoleModel.createBodyLayer());
        builder.put((Object)ModelLayers.TNT_MINECART, (Object)layerDefinition5);
        builder.put((Object)ModelLayers.TRADER_LLAMA, (Object)layerDefinition25);
        builder.put((Object)ModelLayers.TRADER_LLAMA_BABY, (Object)layerDefinition25.apply(LlamaModel.BABY_TRANSFORMER));
        builder.put((Object)ModelLayers.TRIDENT, (Object)TridentModel.createLayer());
        builder.put((Object)ModelLayers.TROPICAL_FISH_LARGE, (Object)TropicalFishModelB.createBodyLayer(CubeDeformation.NONE));
        builder.put((Object)ModelLayers.TROPICAL_FISH_LARGE_PATTERN, (Object)TropicalFishModelB.createBodyLayer(FISH_PATTERN_DEFORMATION));
        builder.put((Object)ModelLayers.TROPICAL_FISH_SMALL, (Object)TropicalFishModelA.createBodyLayer(CubeDeformation.NONE));
        builder.put((Object)ModelLayers.TROPICAL_FISH_SMALL_PATTERN, (Object)TropicalFishModelA.createBodyLayer(FISH_PATTERN_DEFORMATION));
        builder.put((Object)ModelLayers.TURTLE, (Object)layerDefinition44);
        builder.put((Object)ModelLayers.TURTLE_BABY, (Object)layerDefinition44.apply(TurtleModel.BABY_TRANSFORMER));
        builder.put((Object)ModelLayers.VEX, (Object)VexModel.createBodyLayer());
        builder.put((Object)ModelLayers.VILLAGER, (Object)layerDefinition31);
        builder.put((Object)ModelLayers.VILLAGER_BABY, (Object)layerDefinition31.apply(VillagerModel.BABY_TRANSFORMER));
        builder.put((Object)ModelLayers.VINDICATOR, (Object)layerDefinition11);
        builder.put((Object)ModelLayers.WARDEN, (Object)WardenModel.createBodyLayer());
        builder.put((Object)ModelLayers.WARM_COW, (Object)layerDefinition45);
        builder.put((Object)ModelLayers.WARM_COW_BABY, (Object)layerDefinition45.apply(CowModel.BABY_TRANSFORMER));
        builder.put((Object)ModelLayers.WANDERING_TRADER, (Object)layerDefinition31);
        builder.put((Object)ModelLayers.WIND_CHARGE, (Object)WindChargeModel.createBodyLayer());
        builder.put((Object)ModelLayers.WITCH, (Object)WitchModel.createBodyLayer().apply(meshTransformer));
        builder.put((Object)ModelLayers.WITHER, (Object)WitherBossModel.createBodyLayer(CubeDeformation.NONE));
        builder.put((Object)ModelLayers.WITHER_ARMOR, (Object)WitherBossModel.createBodyLayer(INNER_ARMOR_DEFORMATION));
        builder.put((Object)ModelLayers.WITHER_SKULL, (Object)WitherSkullRenderer.createSkullLayer());
        MeshTransformer meshTransformer5 = MeshTransformer.scaling(1.2f);
        builder.put((Object)ModelLayers.WITHER_SKELETON, (Object)layerDefinition30.apply(meshTransformer5));
        builder.put((Object)ModelLayers.WITHER_SKELETON_INNER_ARMOR, (Object)layerDefinition4.apply(meshTransformer5));
        builder.put((Object)ModelLayers.WITHER_SKELETON_OUTER_ARMOR, (Object)layerDefinition2.apply(meshTransformer5));
        builder.put((Object)ModelLayers.WITHER_SKELETON_SKULL, (Object)layerDefinition6);
        builder.put((Object)ModelLayers.WOLF, (Object)layerDefinition46);
        builder.put((Object)ModelLayers.WOLF_ARMOR, (Object)layerDefinition47);
        builder.put((Object)ModelLayers.WOLF_BABY, (Object)layerDefinition46.apply(WolfModel.BABY_TRANSFORMER));
        builder.put((Object)ModelLayers.WOLF_BABY_ARMOR, (Object)layerDefinition47.apply(WolfModel.BABY_TRANSFORMER));
        builder.put((Object)ModelLayers.ZOGLIN, (Object)layerDefinition28);
        builder.put((Object)ModelLayers.ZOGLIN_BABY, (Object)layerDefinition29);
        builder.put((Object)ModelLayers.ZOMBIE, (Object)layerDefinition);
        builder.put((Object)ModelLayers.ZOMBIE_INNER_ARMOR, (Object)layerDefinition4);
        builder.put((Object)ModelLayers.ZOMBIE_OUTER_ARMOR, (Object)layerDefinition2);
        builder.put((Object)ModelLayers.ZOMBIE_BABY, (Object)layerDefinition.apply(HumanoidModel.BABY_TRANSFORMER));
        builder.put((Object)ModelLayers.ZOMBIE_BABY_INNER_ARMOR, (Object)layerDefinition4.apply(HumanoidModel.BABY_TRANSFORMER));
        builder.put((Object)ModelLayers.ZOMBIE_BABY_OUTER_ARMOR, (Object)layerDefinition2.apply(HumanoidModel.BABY_TRANSFORMER));
        builder.put((Object)ModelLayers.ZOMBIE_HEAD, (Object)layerDefinition24);
        builder.put((Object)ModelLayers.ZOMBIE_HORSE, (Object)layerDefinition7);
        builder.put((Object)ModelLayers.ZOMBIE_HORSE_BABY, (Object)layerDefinition8);
        builder.put((Object)ModelLayers.ZOMBIE_HORSE_SADDLE, (Object)layerDefinition9);
        builder.put((Object)ModelLayers.ZOMBIE_HORSE_BABY_SADDLE, (Object)layerDefinition10);
        builder.put((Object)ModelLayers.ZOMBIE_VILLAGER, (Object)layerDefinition48);
        builder.put((Object)ModelLayers.ZOMBIE_VILLAGER_INNER_ARMOR, (Object)ZombieVillagerModel.createArmorLayer(INNER_ARMOR_DEFORMATION));
        builder.put((Object)ModelLayers.ZOMBIE_VILLAGER_OUTER_ARMOR, (Object)ZombieVillagerModel.createArmorLayer(OUTER_ARMOR_DEFORMATION));
        builder.put((Object)ModelLayers.ZOMBIE_VILLAGER_BABY, (Object)layerDefinition48.apply(HumanoidModel.BABY_TRANSFORMER));
        builder.put((Object)ModelLayers.ZOMBIE_VILLAGER_BABY_INNER_ARMOR, (Object)ZombieVillagerModel.createArmorLayer(INNER_ARMOR_DEFORMATION).apply(HumanoidModel.BABY_TRANSFORMER));
        builder.put((Object)ModelLayers.ZOMBIE_VILLAGER_BABY_OUTER_ARMOR, (Object)ZombieVillagerModel.createArmorLayer(OUTER_ARMOR_DEFORMATION).apply(HumanoidModel.BABY_TRANSFORMER));
        builder.put((Object)ModelLayers.ZOMBIFIED_PIGLIN, (Object)layerDefinition22);
        builder.put((Object)ModelLayers.ZOMBIFIED_PIGLIN_INNER_ARMOR, (Object)layerDefinition4);
        builder.put((Object)ModelLayers.ZOMBIFIED_PIGLIN_OUTER_ARMOR, (Object)layerDefinition3);
        builder.put((Object)ModelLayers.ZOMBIFIED_PIGLIN_BABY, (Object)layerDefinition22.apply(HumanoidModel.BABY_TRANSFORMER));
        builder.put((Object)ModelLayers.ZOMBIFIED_PIGLIN_BABY_INNER_ARMOR, (Object)layerDefinition4.apply(HumanoidModel.BABY_TRANSFORMER));
        builder.put((Object)ModelLayers.ZOMBIFIED_PIGLIN_BABY_OUTER_ARMOR, (Object)layerDefinition3.apply(HumanoidModel.BABY_TRANSFORMER));
        builder.put((Object)ModelLayers.BAMBOO_RAFT, (Object)RaftModel.createRaftModel());
        builder.put((Object)ModelLayers.BAMBOO_CHEST_RAFT, (Object)RaftModel.createChestRaftModel());
        LayerDefinition layerDefinition57 = BoatModel.createBoatModel();
        LayerDefinition layerDefinition58 = BoatModel.createChestBoatModel();
        builder.put((Object)ModelLayers.OAK_BOAT, (Object)layerDefinition57);
        builder.put((Object)ModelLayers.OAK_CHEST_BOAT, (Object)layerDefinition58);
        builder.put((Object)ModelLayers.SPRUCE_BOAT, (Object)layerDefinition57);
        builder.put((Object)ModelLayers.SPRUCE_CHEST_BOAT, (Object)layerDefinition58);
        builder.put((Object)ModelLayers.BIRCH_BOAT, (Object)layerDefinition57);
        builder.put((Object)ModelLayers.BIRCH_CHEST_BOAT, (Object)layerDefinition58);
        builder.put((Object)ModelLayers.JUNGLE_BOAT, (Object)layerDefinition57);
        builder.put((Object)ModelLayers.JUNGLE_CHEST_BOAT, (Object)layerDefinition58);
        builder.put((Object)ModelLayers.ACACIA_BOAT, (Object)layerDefinition57);
        builder.put((Object)ModelLayers.ACACIA_CHEST_BOAT, (Object)layerDefinition58);
        builder.put((Object)ModelLayers.CHERRY_BOAT, (Object)layerDefinition57);
        builder.put((Object)ModelLayers.CHERRY_CHEST_BOAT, (Object)layerDefinition58);
        builder.put((Object)ModelLayers.DARK_OAK_BOAT, (Object)layerDefinition57);
        builder.put((Object)ModelLayers.DARK_OAK_CHEST_BOAT, (Object)layerDefinition58);
        builder.put((Object)ModelLayers.PALE_OAK_BOAT, (Object)layerDefinition57);
        builder.put((Object)ModelLayers.PALE_OAK_CHEST_BOAT, (Object)layerDefinition58);
        builder.put((Object)ModelLayers.MANGROVE_BOAT, (Object)layerDefinition57);
        builder.put((Object)ModelLayers.MANGROVE_CHEST_BOAT, (Object)layerDefinition58);
        LayerDefinition layerDefinition59 = SignRenderer.createSignLayer(true);
        LayerDefinition layerDefinition60 = SignRenderer.createSignLayer(false);
        WoodType.values().forEach(woodType -> {
            builder.put((Object)ModelLayers.createStandingSignModelName(woodType), (Object)layerDefinition59);
            builder.put((Object)ModelLayers.createWallSignModelName(woodType), (Object)layerDefinition60);
            for (HangingSignRenderer.AttachmentType attachmentType : HangingSignRenderer.AttachmentType.values()) {
                LayerDefinition layerDefinition3 = HangingSignRenderer.createHangingSignLayer(attachmentType);
                builder.put((Object)ModelLayers.createHangingSignModelName(woodType, attachmentType), (Object)layerDefinition3);
            }
        });
        ImmutableMap immutableMap = builder.build();
        List list = ModelLayers.getKnownLocations().filter(modelLayerLocation -> !immutableMap.containsKey(modelLayerLocation)).collect(Collectors.toList());
        if (!list.isEmpty()) {
            throw new IllegalStateException("Missing layer definitions: " + String.valueOf(list));
        }
        return immutableMap;
    }
}

